import "./date.js";
import "./error_messages.js";
import "./modals.js";
import "./password.js";
import "./phone.js";
import "./random_generate.js";
import "./roles.js";
import "./user_agreement.js";
import "./validation.js";